env:
  global:
    - secure: NANRAnlJExPdWwHJYJ5sEaMaa7r4XiRExY5ebQ3uETiFTPulb6jSkbbSMpTccjF13b6OL3wirJltD67V3pUGGi3biRoZW+dbIy2RJb+qyk0ZICdV6R6/x8vFabtiE3CiiC5GKgC4OKeze8fuwuXXnOK5DPAKwAMb7/MydrsXhf+hmzvdhcKQSkAfPPSJtIarMWQAU8A1Dqr/xFTUJBM0FWVZFS/qopz460VUhj9aS50OgwLtuIBZaiEPWUeR2mVP+WOszlcCtc8qU7kB06b+t83iwR+aEs+cA60svebWt3pM0TVw3WDFqZ0LWm0kgB8XtyPndZ14KMX8LTyWxb8Tbmjg3BEMBbmKTUJ4H3BjLKZXo730sC5AaCOITMSkbh5pbwAO9y6+qonnGiMfHdlap/HuEchBIxrtjum4avB3MuFEpRa5zbGXSSVk5paSKzOo0tDq4PWESfWfqUNE/vV0FTTt3BEF6kBT5gSXjIUaYjmEXKAtBKOxsfPklFbILmo5jBF3W5Uc2bGLnPcoxvu4W0UUOMS8N2AmflOKtjpVbQO5Q5KQNXg2K4mAJAjGmSxqRH7jrpdhJRqlAWQ2y0JvwYtExsyVNQVqhiha6C496U8J87KgBVGv5EwErMLMrn2yM4ICiHPON/jWaK9IwbbcWiUdJ+vRD7oW79+hIqviXgY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/CoinBlockersLists-hosts_optional_git_ZeroDot1
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install dead-hosts-launcher

script:
  - dead_hosts_launcher


notifications:
  email:
    recipients:
      - dead-hosts@funilrys.com
    on_success: never
    on_failure: always
