dist: bionic
env:
    global:
    -   secure: NANRAnlJExPdWwHJYJ5sEaMaa7r4XiRExY5ebQ3uETiFTPulb6jSkbbSMpTccjF13b6OL3wirJltD67V3pUGGi3biRoZW+dbIy2RJb+qyk0ZICdV6R6/x8vFabtiE3CiiC5GKgC4OKeze8fuwuXXnOK5DPAKwAMb7/MydrsXhf+hmzvdhcKQSkAfPPSJtIarMWQAU8A1Dqr/xFTUJBM0FWVZFS/qopz460VUhj9aS50OgwLtuIBZaiEPWUeR2mVP+WOszlcCtc8qU7kB06b+t83iwR+aEs+cA60svebWt3pM0TVw3WDFqZ0LWm0kgB8XtyPndZ14KMX8LTyWxb8Tbmjg3BEMBbmKTUJ4H3BjLKZXo730sC5AaCOITMSkbh5pbwAO9y6+qonnGiMfHdlap/HuEchBIxrtjum4avB3MuFEpRa5zbGXSSVk5paSKzOo0tDq4PWESfWfqUNE/vV0FTTt3BEF6kBT5gSXjIUaYjmEXKAtBKOxsfPklFbILmo5jBF3W5Uc2bGLnPcoxvu4W0UUOMS8N2AmflOKtjpVbQO5Q5KQNXg2K4mAJAjGmSxqRH7jrpdhJRqlAWQ2y0JvwYtExsyVNQVqhiha6C496U8J87KgBVGv5EwErMLMrn2yM4ICiHPON/jWaK9IwbbcWiUdJ+vRD7oW79+hIqviXgY=
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- conda activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
